spring:
  datasource:
    url: jdbc:mysql://117.72.8.221:3124/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: matt
    password: 5qs2pLjw
  data:
    redis:
      host: 117.72.8.221
      port: 4399
      password: D!J?OMca
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.8.221:4848
        namespace: easy-cloud
        username: nacos
        password: zwcb3axb
dubbo:
  application:
    qos-port: 23336
  scan:
    # 接口实现类扫描
    base-packages: com.easy.**.service
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ip:
      port: 9999
      app-name: easy-job-executor
      access-token: default_token
      log-path: ./logs/xxlJob/
      log-retention-days: 7