server:
  port: 30420
  netty:
    connection-timeout: 60000
spring:
  application:
    name: easy-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos
    gateway:
      routes:
        - metadata:
            serviceName: 'easy-authorize'
          id: easy-authorize         # 路由ID
          uri: lb://easy-authorize   # 目标服务URI
          predicates:
            - Path=/authorize/**
          filters:
            - StripPrefix=1
        - metadata:
            serviceName: 'easy-services-system'
          id: easy-service-system         # 路由ID
          uri: lb://easy-service-system   # 目标服务URI
          predicates:
            - Path=/service-system/**
          filters:
            - StripPrefix=1
    sentinel:
      filter:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
  file:
    path: ./logs
  config: classpath:Spring-logback.xml

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      oas3:
        url: /v3/api-docs?group=default
      excluded-services:
        - easy-gateway
#    strategy: manual
#    routes:
#      - name: 认证服务
#        # 真实子服务访问url地址-提供OpenAPI的文档
#        url: /authorize/v3/api-docs?group=default
#        service-name: easy-authorize
#        # 路由前缀
#        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
#        context-path: /authorize
#        order: 2
#      - name: 系统服务
#        url: /service-system/v3/api-docs?group=default
#        service-name: easy-service-system
#        context-path: /service-system
#        order: 3