server:
  port: 9527
  netty:
    connection-timeout: 60000
spring:
  application:
    name: xyaq-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos
    gateway:
      routes:
        - metadata:
            serviceName: 'xyaq-services-system'
          id: xyaq-service-system         # 路由ID
          uri: lb://xyaq-service-system   # 目标服务URI
          predicates:
            - Path=/serviceSystem/**
          filters:
            - StripPrefix=1
    sentinel:
      filter:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    routes:
      - name: 系统服务
        url: /serviceSystem/v3/api-docs?group=default
        service-name: xyaq-service-system
        order: 2