spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3124/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: matt
    password: 5qs2pLjw
  data:
    redis:
      host: 127.0.0.1
      port: 4399
      password: D!J?OMca
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:4848
        namespace: easy-cloud
        username: nacos
        password: zwcb3axb