spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.103:13310/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: hkzs
    password: dev123456
  data:
    redis:
      host: 192.168.200.103
      port: 16379
      password: 123456
      database: 14
      # 连接超时时间（毫秒）
      timeout: 1000
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos