spring:
  datasource:
    url: jdbc:mysql://120.48.20.27:3124/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: matt
    password: 5qs2pLjw
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.20.27:4848
        namespace: easy-cloud
        username: nacos
        password: zwcb3axb
# minio
minio:
  endpoint: http://192.168.199.15:9090
  accessKey: minio
  secretKey: Rxr!2Sw9
  bucketName: jydn
  previewExpiry: 0