spring:
  datasource:
    url: jdbc:mysql://117.72.8.221:3124/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: matt
    password: 5qs2pLjw
  data:
    redis:
      host: 117.72.8.221
      port: 4399
      password: D!J?OMca
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.8.221:4848
        namespace: easy-cloud
        username: nacos
        password: zwcb3axb
# minio
minio:
  endpoint: http://117.72.8.221:9090
  accessKey: minio
  secretKey: Rxr!2Sw9
  bucketName: test
  previewExpiry: 0