server:
  port: 30421
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 20
spring:
  application:
    name: xyaq-authorize
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos
sa-token:
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
  token-name: AQ-Token

logging:
  level:
    root: info
  file:
    path: ./logs
  config: classpath:Spring-logback.xml