spring:
  data:
    redis:
      host: 127.0.0.1
      port: 4399
      password: D!J?OMca
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:4848
        namespace: easy-cloud
        username: nacos
        password: zwcb3axb