spring:
  data:
    redis:
      host: 192.168.200.103
      port: 16379
      password: 123456
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos